spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: orgdirectory-service
          uri: lb://orgdirectory-service
          predicates:
            - Path=/orgdirectory/**
          filters:
            - StripPrefix=1
        - id: organization-service
          uri: lb://organization-service-wildfly
          predicates:
            - Path=/organizations/**
          filters:
            - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka/

ribbon:
  eureka:
    enabled: true