server:
  port: 8081

first-service:
  base-url: http://organization-service-wildfly:8080/first-service/organizations

eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info