FROM quay.io/wildfly/wildfly:latest

RUN /opt/jboss/wildfly/bin/add-user.sh admin admin --silent

RUN /opt/jboss/wildfly/bin/add-user.sh -a -u admin -p admin --silent

COPY ejb-module/build/libs/organization-ejb.jar /opt/jboss/wildfly/standalone/deployments/

COPY wildfly-config/configure-datasource.cli /opt/jboss/wildfly/
COPY wildfly-config/configure-ejb-pool.cli /opt/jboss/wildfly/configure-ejb-pool.cli
COPY wildfly-config/configure-remoting.cli /opt/jboss/wildfly/configure-remoting.cli

RUN /opt/jboss/wildfly/bin/jboss-cli.sh --file=/opt/jboss/wildfly/configure-ejb-pool.cli || true

RUN curl -o /opt/jboss/wildfly/postgresql.jar https://jdbc.postgresql.org/download/postgresql-42.7.4.jar && \
    /opt/jboss/wildfly/bin/jboss-cli.sh --file=/opt/jboss/wildfly/configure-datasource.cli && \
    /opt/jboss/wildfly/bin/jboss-cli.sh --file=/opt/jboss/wildfly/configure-remoting.cli || true

EXPOSE 8080 9990

ENTRYPOINT ["/opt/jboss/wildfly/bin/standalone.sh", "-b", "0.0.0.0", "-bmanagement", "0.0.0.0"]

