FROM quay.io/wildfly/wildfly:latest

RUN /opt/jboss/wildfly/bin/add-user.sh admin admin --silent

COPY ejb-module/build/libs/organization-ejb.jar /opt/jboss/wildfly/standalone/deployments/
COPY web-module/build/libs/web-module.war /opt/jboss/wildfly/standalone/deployments/

COPY wildfly-config/configure-datasource.cli /opt/jboss/wildfly/
COPY wildfly-config/configure-ejb-pool.cli   /opt/jboss/wildfly/configure-ejb-pool.cli

RUN /opt/jboss/wildfly/bin/jboss-cli.sh --file=/opt/jboss/wildfly/configure-ejb-pool.cli

COPY web-module/register-consul.sh /opt/jboss/wildfly/bin/register-consul.sh

EXPOSE 8080 9990

ENTRYPOINT ["/bin/sh", "-c", "/opt/jboss/wildfly/bin/register-consul.sh & exec /opt/jboss/wildfly/bin/standalone.sh -b 0.0.0.0 -bmanagement 0.0.0.0"]