FROM quay.io/wildfly/wildfly:latest

RUN /opt/jboss/wildfly/bin/add-user.sh admin admin --silent

COPY web-module/build/libs/web-module.war /opt/jboss/wildfly/standalone/deployments/

EXPOSE 8080 9990

ENTRYPOINT ["/opt/jboss/wildfly/bin/standalone.sh", "-b", "0.0.0.0", "-bmanagement", "0.0.0.0"]

